// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode,
} from "ohm-js";

export interface ArithmeticActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: IterationNode) => T;
  Stmt_letBind?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
    arg3: NonterminalNode,
  ) => T;
  Stmt_exprOnly?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Stmt?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Exp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExp_plus?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  AddExp_minus?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  AddExp_mul?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExp_times?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  MulExp_divide?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  MulExp_unary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExp_pos?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
  ) => T;
  UnaryExp_neg?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
  ) => T;
  UnaryExp_pri?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp_paren?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
  ) => T;
  PriExp_lit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp_var?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ident?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: IterationNode,
  ) => T;
  number?: (
    this: NonterminalNode,
    arg0: IterationNode,
    arg1: IterationNode,
    arg2: IterationNode,
  ) => T;
}

export interface ArithmeticSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
}

export interface ArithmeticGrammar extends Grammar {
  createSemantics(): ArithmeticSemantics;
  extendSemantics(superSemantics: ArithmeticSemantics): ArithmeticSemantics;
}

declare const grammar: ArithmeticGrammar;
export default grammar;
