// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface ArithmeticActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: IterationNode) => T;
  Stmt?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Exp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AssignExp_assign?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AssignExp_or?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AssignExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExp_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  OrExp_and?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExp_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  AndExp_not?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NotExp_not?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  NotExp_cmp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NotExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CmpExp_gte?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_lte?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_eq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_neq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_gt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_lt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CmpExp_add?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CmpExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExp_plus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExp_minus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExp_mul?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExp_times?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExp_divide?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExp_unary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExp_pos?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExp_neg?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExp_pri?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PriExp_lit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp_var?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  and_kw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  or_kw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  not_kw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ident?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
}

export interface ArithmeticSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
}

export interface ArithmeticGrammar extends Grammar {
  createSemantics(): ArithmeticSemantics;
  extendSemantics(superSemantics: ArithmeticSemantics): ArithmeticSemantics;
}

declare const grammar: ArithmeticGrammar;
export default grammar;

