// AUTOGENERATED FILE
// This file was generated from json.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface JsonMiniActionDict<T> extends BaseActionDict<T> {
  space?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Json?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value_obj?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value_arr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value_str?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value_num?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value_true?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Value_false?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Value_null?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Array?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: TerminalNode) => T;
  Object?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: TerminalNode) => T;
  Pair?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  stringChar_esc?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  stringChar_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode, arg3: IterationNode) => T;
  intPart_zero?: (this: NonterminalNode, arg0: TerminalNode) => T;
  intPart_nzDigits?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  intPart?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  fracPart?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  expPart?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  nz?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface JsonMiniSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: JsonMiniActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: JsonMiniActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: JsonMiniActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: JsonMiniActionDict<T>): this;
}

export interface JsonMiniGrammar extends Grammar {
  createSemantics(): JsonMiniSemantics;
  extendSemantics(superSemantics: JsonMiniSemantics): JsonMiniSemantics;
}

declare const grammar: JsonMiniGrammar;
export default grammar;

