// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface LuckyScriptActionDict<T> extends BaseActionDict<T> {
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  nl?: (this: NonterminalNode, arg0: IterationNode) => T;
  comment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  keyword?: (this: NonterminalNode, arg0: TerminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  sep?: (this: NonterminalNode, arg0: TerminalNode) => T;
  nz?: (this: NonterminalNode, arg0: TerminalNode) => T;
  fracPart?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  zeroNum_withDot?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  zeroNum_bare?: (this: NonterminalNode, arg0: TerminalNode) => T;
  zeroNum?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  intPart?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode) => T;
  intNum?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  dotLeadNum?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  stringChar_esc?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  stringChar_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ifKeyword?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ParamList?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  ArgList?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  BlockStmts?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  AssignOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  CompareOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Program?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  Stmt_funDecl?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Stmt_if?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: NonterminalNode, arg5: NonterminalNode, arg6: NonterminalNode, arg7: TerminalNode) => T;
  Stmt_while?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: NonterminalNode, arg5: TerminalNode) => T;
  Stmt_break?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Stmt_continue?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Stmt_return?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Stmt_letAssign?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode) => T;
  Stmt_exprStmt?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Stmt?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ElseIfChain?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  OptElse?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  FunDecl?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: TerminalNode, arg6: IterationNode, arg7: NonterminalNode, arg8: TerminalNode) => T;
  Expression_assign?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Expression_anonFun?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Expression_orExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Expression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Assignment?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  AnonymousFun?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode, arg4: NonterminalNode) => T;
  AnonSuffix_blockForm?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  AnonSuffix_shortForm?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AnonSuffix?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExpr_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  OrExpr_pass?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExpr_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AndExpr_pass?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NotExpr_not?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  NotExpr_cmp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NotExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CmpExpr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  ArithExpr_addSub?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  ArithExpr_pass?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ArithExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Term_mulDiv?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Term_pass?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Term?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Factor_unary?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Factor_pow?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Factor?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Power_pow?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Power_atom?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Power?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Atom_num?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Atom_str?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Atom_nothing?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Atom_true?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Atom_false?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Atom_call?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  Atom_ident?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Atom_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Atom?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  numberLex?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface LuckyScriptSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: LuckyScriptActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: LuckyScriptActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: LuckyScriptActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: LuckyScriptActionDict<T>): this;
}

export interface LuckyScriptGrammar extends Grammar {
  createSemantics(): LuckyScriptSemantics;
  extendSemantics(superSemantics: LuckyScriptSemantics): LuckyScriptSemantics;
}

declare const grammar: LuckyScriptGrammar;
export default grammar;

