name: Lark Sandbox

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lark-sandbox

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"

      - run: make lint
      - run: make test
